### ISSUE TITLE
Fountain::Api::Notes.create raises an exception incorrectly

### ISSUE THREAD

**Issue by srgoldman** [Studiosity/fountain-ruby#1]
It raises: Fountain::HTTPError: Invalid http response code: 201
but 201 is exactly the correct response for an HTTP create request (which this is).

**Comment by abrom** [comment]
Thanks @srgoldman 👍 

Unfortunately it looks like the Fountain documentation is wrong :/ 

Anyway, issue has been fixed in v0.0.11

**Comment by srgoldman** [comment]
Thank you! Have you thought about putting together some mock helpers (like Stripe has)? Also, just wanted to express appreciation for you putting this together. While it wouldn't have been hard to implement from scratch, your work saved me a fair bit of time.

**Comment by abrom** [comment]
Hi @srgoldman

Not a problem. I've already got API mocks in the spec tests. The problem was that the spec tests were written to match the API documentation (which was/is wrong)
